---
image:
  repository: "opensearchproject/opensearch"
  tag: "2.12.0"
  pullPolicy: "IfNotPresent"

majorVersion: "2"

nodeGroup: "machinelearning"

roles:
  - ml

replicas: 2

opensearchJavaOpts: "-Xmx16G -Xms16G"

resources:
  requests:
    cpu: "4"
    memory: "32Gi"
