image:
  repository: "opensearchproject/opensearch"
  tag: "2.12.0"
  pullPolicy: "IfNotPresent"

majorVersion: "2"

opensearchJavaOpts: "-Xmx24G -Xms24G"

replicas: 4

resources:
  requests:
    cpu: "4"
    memory: "48Gi"

nodeGroup: "data"

roles:
  - ingest
  - data
  - remote_cluster_client

persistence:
  size: 480Gi
